spring:
   datasource:
     url: jdbc:mysql://localhost:3306/lwl
     username: root
     password: dbuser
   jpa:
     hibernate:
       ddl-auto: update #create #update #can create-drop as well
     show-sql: true
     properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
server:
 servlet:
   context-path: /ipl